### ISSUE TITLE
API Tests seem to be failing

### ISSUE THREAD

**Issue by iamutkarshtiwari** [Javicompi/WhatWeath#2]
`CurrentApiServiceTest` and `HourlyApiServiceTest` seem to fail.
Logs: https://gist.github.com/iamutkarshtiwari/cbb6c382f07d20584a19ab45f2c00d52

**Comment by Javicompi** [comment]
It should be fixed now. Seems like I modified the models but didn't update the tests.

**Comment by iamutkarshtiwari** [comment]
Thank you! 🙏 I am learning a lot from your project.

**Comment by Javicompi** [comment]
Thanks you too for pointing it out.
